# Site settings
title: Artists Theme
email: your-email@domain.com
description: Thinker // Designer // Flickrer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

sass:
  sass_dir: assets/css
  style: :nested


